"""
Answer synthesizer — builds grounded prompts and wires citations.

The synthesizer:
1. Takes a user query + list of NormalizedDocuments
2. Builds a structured RAG prompt injecting source chunks as numbered context
3. Instructs the LLM to use [1], [2]... inline citation format
4. Returns a streaming token generator
5. Runs the citation grounder post-generation (non-blocking)
"""
from __future__ import annotations

import logging
from typing import AsyncIterator

from cloudsearch_shared.document import NormalizedDocument
from .providers.base_provider import LLMConfig, LLMMessage

logger = logging.getLogger(__name__)

# Maximum characters of content per source injected into the prompt
MAX_CONTEXT_CHARS_PER_SOURCE = 800
MAX_TOTAL_CONTEXT_CHARS = 12_000

SYSTEM_PROMPT = """You are CloudSearch, an intelligent answer engine.
Your task is to provide a comprehensive, accurate answer to the user's query based ONLY on the provided sources.

Rules:
1. Base your answer strictly on the provided sources. Do not use prior knowledge beyond the sources.
2. Cite every factual claim using inline citation markers like [1], [2] referring to the source numbers.
3. Write in clear, flowing prose. Do not use bullet points unless the query explicitly asks for a list.
4. If the sources are insufficient to answer the query, say so clearly.
5. Keep the answer concise but complete — typically 2-4 paragraphs.
6. Do not repeat the same information from multiple sources; synthesize.
"""

def build_rag_prompt(
    query: str,
    documents: list[NormalizedDocument],
    max_docs: int = 10,
) -> list[LLMMessage]:
    """
    Build the RAG prompt injecting source chunks with [N] numbering.

    Args:
        query:     User query.
        documents: Retrieved, re-ranked source documents.
        max_docs:  Maximum number of sources to inject.

    Returns:
        List of LLMMessage objects ready for the LLM provider.
    """
    docs = documents[:max_docs]
    total_chars = 0
    context_parts = []

    for idx, doc in enumerate(docs, start=1):
        # Truncate each source to avoid context overflow
        content = doc.content[:MAX_CONTEXT_CHARS_PER_SOURCE]
        if total_chars + len(content) > MAX_TOTAL_CONTEXT_CHARS:
            remaining = MAX_TOTAL_CONTEXT_CHARS - total_chars
            content = content[:remaining]

        source_block = (
            f"[{idx}] {doc.title}\n"
            f"URL: {doc.url}\n"
            f"{content}"
        )
        context_parts.append(source_block)
        total_chars += len(source_block)

        if total_chars >= MAX_TOTAL_CONTEXT_CHARS:
            break

    context = "\n\n---\n\n".join(context_parts)

    user_message = (
        f"Sources:\n\n{context}\n\n"
        f"---\n\n"
        f"Query: {query}\n\n"
        f"Answer (cite sources as [1], [2], etc.):"
    )

    return [
        LLMMessage(role="system", content=SYSTEM_PROMPT),
        LLMMessage(role="user", content=user_message),
    ]


async def stream_answer(
    query: str,
    documents: list[NormalizedDocument],
    model_router,
    config: LLMConfig | None = None,
) -> AsyncIterator[str]:
    """
    Stream the synthesized answer token-by-token.

    Args:
        query:        User query.
        documents:    Re-ranked retrieved documents.
        model_router: ModelRouter instance.
        config:       Optional LLM config overrides.

    Yields:
        String tokens as they are generated by the LLM.
    """
    if not documents:
        yield "I couldn't find relevant sources for your query. Please try rephrasing."
        return

    messages = build_rag_prompt(query, documents)

    logger.debug(
        "Synthesizing answer for query %r using %d sources.",
        query[:80],
        len(documents),
    )

    try:
        async for token in model_router.stream_complete(messages, config):
            yield token
    except Exception as exc:
        logger.exception("stream_answer failed: %s", exc)
        yield "\n\n⚠️ An error occurred while generating the answer."
